"""allow_duplicate_sha256

Revision ID: 087027ed40bd
Revises: 0002
Create Date: 2026-01-19 22:49:32.504613

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '087027ed40bd'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('documents_doc_id_key'), 'documents', type_='unique')
    op.drop_constraint(op.f('documents_sha256_key'), 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_doc_id'), table_name='documents')
    op.create_index(op.f('ix_documents_doc_id'), 'documents', ['doc_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_doc_id'), table_name='documents')
    op.create_index(op.f('ix_documents_doc_id'), 'documents', ['doc_id'], unique=False)
    op.create_unique_constraint(op.f('documents_sha256_key'), 'documents', ['sha256'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('documents_doc_id_key'), 'documents', ['doc_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
