"""add_starred_and_reactions

Revision ID: b05bfd4de95e
Revises: cece4bb80715
Create Date: 2026-01-23 19:55:21.290366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05bfd4de95e'
down_revision = 'cece4bb80715'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('reactions', sa.JSON(), nullable=True))
    op.add_column('chat_threads', sa.Column('is_starred', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_threads', 'is_starred')
    op.drop_column('chat_messages', 'reactions')
    # ### end Alembic commands ###
