"""add_chat_branching

Revision ID: cece4bb80715
Revises: 0003_add_chat_tables
Create Date: 2026-01-22 11:29:39.237386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cece4bb80715'
down_revision = '0003_add_chat_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_threads', sa.Column('document_id', sa.Integer(), nullable=True))
    op.add_column('chat_threads', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_threads', 'chat_threads', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'chat_threads', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_threads', type_='foreignkey')
    op.drop_constraint(None, 'chat_threads', type_='foreignkey')
    op.drop_column('chat_threads', 'parent_id')
    op.drop_column('chat_threads', 'document_id')
    # ### end Alembic commands ###
